### PR TITLE
Added Test dependancies to the project, resolution of problem #10

### PR DESCRIPTION
**Pull request by kounkou**
Hey guys,

This merge will setup all the testing purposes tools into the project. This is a massive update. Please don't forget to pull from the stream, you'll need it to have the right coding attitude for the website.

Please let me know of any idea to improve :smile:

### CODE REVIEW

**Comment by rajilsaj** [comment]
Damn all this

**Comment by kounkou** [comment]
Yeah, it's like I exploded the project... logically we need all this environment to work on that website.
This is too much files. I will remove the dependancies from github. But hey, you'll have to add them on your sides yourself. Sounds good?

**Comment by rajilsaj** [comment]
Hi CongoLUG/website,

I'd like to add you to my professional network on LinkedIn.
- Rajil

Confirm that you know Rajil: https://www.linkedin.com/e/v2?e=0-ion4hl08-vx&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Lq0JbBjw&invitationId=6141282985640546304

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ion4hl08-vx&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHQ6VH3GkT9sgAAAVTo4cojIY7f6FU94305URVN8htL5pu3mvfack7hNoiWsk33dLKXPh4RYfAIl1rrrTC1sPEw-tR2puJwI6PXcpaGbVhLH9gE_Fb8g4dibA2eZFg3sBO9ioQveNwtxvPN0pQ91lGy5OGYBR3w5uSBKffPAtUaKRwC7GBuAv4sZCKtDqzAlOnh&eid=0-ion4hl08-vx

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ion4hl08-vx&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Lq0JbBjw&invitationId=6141282985640546304&trk=eml-first_guest_reminder_01-hero-14-accept_text&trkEmail=eml-first_guest_reminder_01-hero-14-accept_text-null-%7E8cmz6i%7Eiowuvdn6%7Ecr

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Lq0JbBjw&invitationId=6141282985640546304&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7E8cmz6i%7Eiowuvdn6%7Ecr

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-8cmz6i-iowuvdn6-cr&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-8cmz6i-iowuvdn6-cr&loid=AQE8h1As_ULARQAAAVUM9PnJ5i1lZey1hJebWziN_Kq8CIBrDpoWmMAywDn_ZVvT32ueGyG7v1aQ-1v5egTUYEUMBjPWjtTg7JkVe1RLPdGxalyzYLpVQLgsU-k9wPvyKIMKw6UpywvR0tf_g3CkuCo-5WVsLmBXejOwSuRGfMYOnbJnyRV_zBnB_yPAFSZnMCWV

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-8cmz6i-iowuvdn6-cr&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-8cmz6i-ip6v2xgg-r1&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=Lq0JbBjw&invitationId=6141282985640546304

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/e/v2?e=-8cmz6i-ip6v2xgg-r1&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Lq0JbBjw&invitationId=6141282985640546304

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-8cmz6i-ip6v2xgg-r1&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-8cmz6i-ip6v2xgg-r1&loid=AQEd9GH3BPLW2AAAAVUw9_lvqcQsj6mN25MQZJzsfqYf94uapQwcHEPIdBpazJgNbsMO_F0qNef6F74lojKI7aETjylqU23Pm12bHpr8JXhonflUTGG8FQ-_2wqLbx5rucBfcOaAF5llcy_x4JgVAIhedIFcnaMZ8mmSVPdW23i8d-3WD5w_d2hxq8S80_v8gcj3

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-8cmz6i-ip6v2xgg-r1&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
