### PR TITLE
Congo lug updates fw38

### PR DESCRIPTION
**Pull request by kounkou**
Hello guys!

I rework the CongoLUG website architecture en created a pull request. Please have a look and let me know if you find anything I can improve before the merge. Else, I am ready to go.

Jacques

### CODE REVIEW

**Comment by rajilsaj** [comment]
OK guy

**Comment by kounkou** [comment]
Awesome! I know you used jquery outside of Angular, this time, I brought jquery inside of Angular, so we'll manage the dependancies the good way ;)

**Comment by rajilsaj** [comment]
It seems that you coded the whole project lol !

**Comment by rajilsaj** [comment]
Mister @python promised us some pelicans but he went silent :)

**Comment by kounkou** [comment]
Not even started :laughing: But this way we have the good architecture for the project.
Going to merge after  I took my diner.
Josh is so french... :fr:

**Comment by rajilsaj** [comment]
Did you pick #jeckyll ? As a Cms tool

**Comment by kounkou** [comment]
Not yet,... Hum, I am more gung-ho about coding the site myself to learn about html5 + angular, jquery, etc. Originally I do C/C++, so trying to get better in those technologies with :octocat:

**Comment by rajilsaj** [comment]
Ok I see

**Comment by rajilsaj** [comment]
I m on mobile till 10 pm but we keep exchanging about architecture ? Already

**Comment by kounkou** [comment]
Okay. No worries. You see the merge by EOD. Take care!

**Comment by rajilsaj** [comment]
Which one ? Oups !

**Comment by kounkou** [comment]
This one :smile:

**Comment by rajilsaj** [comment]
Hi CongoLUG/website,

I'd like to add you to my professional network on LinkedIn.

- Rajil

Confirm that you know Rajil: https://www.linkedin.com/e/v2?e=0-ion4hlfx-fe&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=7nn7U-pR&invitationId=6141282994285010944








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ion4hlfx-fe&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF0JAgHiBxgJAAAAVTo4dfgKSxjR2r9LQKABl36mISlxeFO6J4PCN2sO_DeyD5DpuJHu3INpuA2Iuk09dTS76zDmam8shdVVJ-_oBbrCDdzYDrfvwogJub0tMfnZoE5P-L3dZY1S2Dvt5uuydm2YiQHYxcjO807KvQHfoNf5eEyKEcpAYbjsqv7LwP4a1pmlJ8x&eid=0-ion4hlfx-fe


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ion4hlfx-fe&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Hi CongoLUG/website,

I'd like to add you to my professional network on LinkedIn.

- Rajil

Confirm that you know Rajil: https://www.linkedin.com/e/v2?e=0-ion4hl07-1u&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=6b-J80Yt&invitationId=6141282997162307584








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ion4hl07-1u&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFrZm90EB7_uQAAAVTo4dKN9mU-Z-iCGJljXgkdH4V0AuDB2flOLT4_BmSfklWx-p_M7pzQJEo4Ga7HpvwDOSvyJJhrudsNgTenFFD_DGsH3aPxJjfOongDo3HBRlNx8sp7Sta24BeRK1DB-wWgBlS7GXa2rs9HUdrogtHh9gheEOj8Y9aMRUKmLotEN3-mhBfq&eid=0-ion4hl07-1u


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ion4hl07-1u&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Hi CongoLUG/website,

I'd like to add you to my professional network on LinkedIn.

- Rajil

Confirm that you know Rajil: https://www.linkedin.com/e/v2?e=0-ion4hnqx-uj&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=gsG9JoRf&invitationId=6141282997032280065








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ion4hnqx-uj&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEvpcpybDGEzgAAAVTo4eZVE3xClVHKrrjOl4jfvGdpRVWzjFWB_If0JBAddqjS0Z6Ayl8X-M-Pq68U7ibL20Hk1_5J6k96MX3hmfIoLWkcVzQ9l4mylfClt8AzINTctsTyVzlUuM_Cvh5in66u9ZVDkHdi66fErnVp8t8oZlm-5xIJQGvKX_v0-foxFCf1LnGu&eid=0-ion4hnqx-uj


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ion4hnqx-uj&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Hi CongoLUG/website,

I'd like to add you to my professional network on LinkedIn.

- Rajil

Confirm that you know Rajil: https://www.linkedin.com/e/v2?e=0-ion4hli4-dt&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=rXvX_N_z&invitationId=6141282991256727553








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ion4hli4-dt&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEbtqBeyx0JlAAAAVTo4c_GU8NK1KYt9xjBHe_bytoy4Liv5uieQnUA9mqUOCgOG09gDsWaTgre8N1Rqe0BcjXkk8TebLrT4Gfdpfjrpmi-wRh4U_Ge6ztQJiqIsBnpa-w0kmMJ2AZHn15tsLRON2bcsRjxxAgoiUy-MX8AG4iopCeNmxAO1pSCh5bcPy-aQyAO&eid=0-ion4hli4-dt


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ion4hli4-dt&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Hi CongoLUG/website,

I'd like to add you to my professional network on LinkedIn.

- Rajil

Confirm that you know Rajil: https://www.linkedin.com/e/v2?e=0-ion4i6ax-8f&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=RsgqnJdp&invitationId=6141282988069052416








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ion4i6ax-8f&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGBjywQTmgk8wAAAVTo4kCZ0-TTOzAUg-ufLgPS0vOFXHweFHMJ4pd9HNtB3L3ihsXX2D_XZacucqcTGUkCo3N3FOBLiQuCHUbsGu8Tglv8PXxoIeXPQVTz02_b8yB3rfrduszekt2oLemv6mG3Rn3W6WS1931Ap7MhaKsNw0zGLIF5Zryv2tsyAJL9i3-QifSp&eid=0-ion4i6ax-8f


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ion4i6ax-8f&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=6b-J80Yt&invitationId=6141282997162307584&trk=eml-first_guest_reminder_01-hero-14-accept_text&trkEmail=eml-first_guest_reminder_01-hero-14-accept_text-null-ru8r7k%7Eiowuvdn9%7E1k

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=6b-J80Yt&invitationId=6141282997162307584&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-ru8r7k%7Eiowuvdn9%7E1k





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=ru8r7k-iowuvdn9-1k&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=ru8r7k-iowuvdn9-1k&loid=AQEBbfTDnB-QJwAAAVUM9XK37WbnE2XFyX2a76m7s7eIq59jaRc7iPfbFWr-VKq8stCGq5bVu3dMicxI0wfKt_Ug4z1laErXMgwbeKM5ixelOfqQXPZ4k2UvqqfSd5fVCr3whILTV6JVxYLH3mXSbfTCeNkiQtDEd67ZXziTNpGv3lHsmJOedWmKpDYTOZ-xrrfG

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=ru8r7k-iowuvdn9-1k&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=rXvX_N_z&invitationId=6141282991256727553&trk=eml-first_guest_reminder_01-hero-14-accept_text&trkEmail=eml-first_guest_reminder_01-hero-14-accept_text-null-6o6cc4%7Eiowuv8w1%7E2f

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=rXvX_N_z&invitationId=6141282991256727553&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-6o6cc4%7Eiowuv8w1%7E2f





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=6o6cc4-iowuv8w1-2f&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=6o6cc4-iowuv8w1-2f&loid=AQEZFVTxbkOJXwAAAVUM9q9ROIOu4KGefQlA2K774ZRvEoc6mPckcA_MGlI0XJ-CvU4z6YTQEBdB8o595TLNMFY5LY-BVgyk5hw2hBV35QqgLV8-yv7C3lYVWXhUSOKIUA1WdkktAC3zoXW00XM5WU7eO_iOuDcj0WiBqlUqY6gNLwcVRIjPMRGKdyexoh9UaR5A

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=6o6cc4-iowuv8w1-2f&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=RsgqnJdp&invitationId=6141282988069052416&trk=eml-first_guest_reminder_01-hero-14-accept_text&trkEmail=eml-first_guest_reminder_01-hero-14-accept_text-null-%7E6fflsj%7Eiowuooi0%7Ele

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=RsgqnJdp&invitationId=6141282988069052416&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7E6fflsj%7Eiowuooi0%7Ele





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-6fflsj-iowuooi0-le&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-6fflsj-iowuooi0-le&loid=AQGOwyXD69ywKwAAAVUM9rUQkGF6jU3t016HwOBgTz3vq4rRzFmld81UOBFep6xafgwPoLp5Mf8jMPHAdIG9Iui_SYhV9y49Dug68Yu14d09rC_jgkFrD6_hRLNfe42kay8xLKi-fhG3lArYQjPpX2qYdnuZhXZeLumrfsotTc4YQeY_6m2diPxAsu9UawC8w6eE

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-6fflsj-iowuooi0-le&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=gsG9JoRf&invitationId=6141282997032280065&trk=eml-first_guest_reminder_01-hero-14-accept_text&trkEmail=eml-first_guest_reminder_01-hero-14-accept_text-null-%7Evtyejw%7Eiowuooq5%7Etk

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=gsG9JoRf&invitationId=6141282997032280065&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Evtyejw%7Eiowuooq5%7Etk





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-vtyejw-iowuooq5-tk&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-vtyejw-iowuooq5-tk&loid=AQHe2fq95K_GVAAAAVUM9zyfaDiLh875xMnhZCD3r1pCHYC-Xw1pfJ1hB6sVlNACov5_iyOS_H9Gbu6AtQBDmyy9Mes9Z-ke_-jyU5D-mCje43e-fcLw9ZbOm4SlhmBhgkeQ5mJAcaFSccg7MTfvZoteMEHoGRzxJBPkulhQgIWREU1z3cS636w2Lu-WiO5JGnSB

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-vtyejw-iowuooq5-tk&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=7nn7U-pR&invitationId=6141282994285010944&trk=eml-first_guest_reminder_01-hero-14-accept_text&trkEmail=eml-first_guest_reminder_01-hero-14-accept_text-null-m1tdc1%7Eiowuukcg%7Ext

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=7nn7U-pR&invitationId=6141282994285010944&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-m1tdc1%7Eiowuukcg%7Ext





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=m1tdc1-iowuukcg-xt&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=m1tdc1-iowuukcg-xt&loid=AQHbTG_h2IgoLAAAAVUM-k2h0Cz5G-XsokDQZYB_MiIX3hzMWlrPow_g5lwqN5gLwa9iBvyum5mCN0t05TqRLd3GOHgRDkCYnf1IDhcHehN0SpTQh2I6XyyXU9HCfz1tKF9bTQ67AsGEnmNcfAxb3cg6TmtkNLGI2VSkQ4dBaaWxP7yurxItDGawrhgS-jzuBsQl

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=m1tdc1-iowuukcg-xt&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-vtyejw-ip6v2jv1-z1&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=gsG9JoRf&invitationId=6141282997032280065

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/e/v2?e=-vtyejw-ip6v2jv1-z1&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=gsG9JoRf&invitationId=6141282997032280065





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-vtyejw-ip6v2jv1-z1&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-vtyejw-ip6v2jv1-z1&loid=AQH6wP3otcdghAAAAVUw9uh0lDKtv0rKgU5m_oMlv8qAhLjl7EmJV20dsB1NivnY04uS_yc8WGE2gyxRNadM4tE2ZeJrDWgkdOnyx9T84E8o2K64-cVm-Jswb6Zv9Pfm3U02fNmu5GsDoYvGzr8YmmLzbk_FQ-info93YqxXvxlJlV3q-BTD8HtrICbL0Inc-XDV

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-vtyejw-ip6v2jv1-z1&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=ru8r7k-ip6v2pvm-zy&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=6b-J80Yt&invitationId=6141282997162307584

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/e/v2?e=ru8r7k-ip6v2pvm-zy&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=6b-J80Yt&invitationId=6141282997162307584





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=ru8r7k-ip6v2pvm-zy&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=ru8r7k-ip6v2pvm-zy&loid=AQHsGz0JRW_PmgAAAVUw9xYOdiBC-5_thDFW3pemXTiMKbbsUS7rXvcPtVMGXiwDjIDKYj66HTH0m1bZXQ3g15v5qdhRTNssTqtFgxCbNP4djFbKc1pCmTlF_URydnpzsjmCTUYF2Z4SrLubce1pqlcH8c090c-ANNV3xBh4lZEI756z914xcrPSf2PR8j14oS9v

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=ru8r7k-ip6v2pvm-zy&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=m1tdc1-ip6v2prs-di&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=7nn7U-pR&invitationId=6141282994285010944

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/e/v2?e=m1tdc1-ip6v2prs-di&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=7nn7U-pR&invitationId=6141282994285010944





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=m1tdc1-ip6v2prs-di&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=m1tdc1-ip6v2prs-di&loid=AQEvTlPoYykO8wAAAVUw98h7odcWkZzHDGFbGQHDc4hNbQpjhUIN4YyEutNeLGF8i3dFT--6PDKd4xTJJYhzZ5-9y2t7W2tIb4DJ_PuZoGaK2yFesSObio4SX1QKO7NBa5ynbgNOkGvKNxk4zN0lMOJZrF4VQ5BMiALrg14dWf6ZjVHjxwKxDNg-HDqqK_cPLcXa

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=m1tdc1-ip6v2prs-di&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=6o6cc4-ip6v32td-5e&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=rXvX_N_z&invitationId=6141282991256727553

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/e/v2?e=6o6cc4-ip6v32td-5e&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=rXvX_N_z&invitationId=6141282991256727553





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=6o6cc4-ip6v32td-5e&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=6o6cc4-ip6v32td-5e&loid=AQFTzAxMK3qXAgAAAVUw-dAOEhyfxCXM6oMIGC0wnqRUzVykUZ4eVtNP5Uf1tbii6YJgRLyxM8sc5UnxfOwi2eXK6yl-z7ztHWF9u1l-vBbLTUOAqlI5d_Ea2bYD7SNdla1J-uMKU5RcAYk6EePiu0zK_Dcv5pFbrC-dHUK1YJUScBjvDVcjPL39RrkRZT7G18D5

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=6o6cc4-ip6v32td-5e&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-6fflsj-ip6v2jv1-a5&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=RsgqnJdp&invitationId=6141282988069052416

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/e/v2?e=-6fflsj-ip6v2jv1-a5&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=RsgqnJdp&invitationId=6141282988069052416





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-6fflsj-ip6v2jv1-a5&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-6fflsj-ip6v2jv1-a5&loid=AQEKCpQ0fCMTvgAAAVUw_suhIigwqIjE_oeiqABsDkKFT2CFur3GOjSfH5LCx0ZLMtMsq3FXPb1Z_EATtw55FZgR6Yf5a4-pE_jjDklsnAvKEYuimJRfhVruHZnuyuG7rJrbUbDQHXggoIPWYefV1q2PfKyPsduxRLYUBrCoQ5VclT6L9W0h3r5ercvWl7dIVBQa

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-6fflsj-ip6v2jv1-a5&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
